import React, { createContext, useContext, useState, useEffect } from 'react';

export const translations = {
  en: {
    appTitle: 'CoalGuard OS',
    appSubtitle: 'AI Smart Governance & DGMS Compliance Monitoring System',
    adminCommandCenter: 'Mine Operations & Compliance Command Center',
    adminSubtitle: 'Autonomous AI Ingestion, DGMS Audit & Incident Operations Hub',
    userDashboard: 'Field Inspector Portal',
    signOut: 'Sign Out',
    exportCsv: 'Export Statutory Audit CSV',
    adminView: 'Command Center',
    userView: 'Inspector Portal',
    liveRadar: 'LIVE DGMS COMPLIANCE RADAR — 4 COALFIELDS CONNECTED',
    raiseIssueTitle: 'Report Hazard / Statutory Violation',
    raiseIssueSubtitle: 'Log mine safety observations, environmental non-compliance, or equipment anomalies with GPS & photo evidence.',
    mineSiteLabel: 'Coalfield / Mine Site Location',
    mineSitePlaceholder: 'e.g. Jharia Colliery - Pit 4 (Underground)',
    issueTitleLabel: 'Incident / Violation Title',
    issueTitlePlaceholder: 'e.g. Methane Gas Level 1.4% at Shaft-B or Dumper Hydraulic Failure',
    problemDescriptionLabel: 'Detailed Hazard Description & Field Notes',
    problemDescriptionPlaceholder: 'Provide thorough field observations: exact pit zone, gas sensor readings, affected shift, equipment ID...',
    attachmentsLabel: 'Attach Inspection Photos / Gas Logs (Optional, up to 5 files - Images, PDF)',
    submitButton: 'Transmit to AI Safety Command →',
    submittingButton: 'AI Analyzing DGMS Compliance & Routing...',
    mySubmittedIssues: 'My Field Inspection Logs',
    noIssuesFound: 'No mine violations logged yet. Use the form above to record your first geo-tagged inspection report.',
    duplicateAlertTitle: '⚠️ AI Alert: Similar Hazard Recently Reported in this Zone!',
    duplicateAlertDesc: 'Our AI found active safety incidents matching this location and hazard signature. Please verify if this is already being addressed:',
    dismissContinue: 'Dismiss & Continue Logging',
    viewMatch: 'View Incident →',
    problemDescription: 'Hazard & Incident Observation',
    geminiExecutiveBrief: 'AI DGMS Diagnostic Brief',
    confidence: 'AI Confidence',
    troubleshootingPlan: 'Standard Operating Procedure (SOP) & Containment Protocol',
    guidance: 'Action SOP',
    insertToReply: 'Insert to Resolution Log',
    liveResolutionThread: 'Live Operations & Inspector Communication Channel',
    noMessagesYet: 'No messages yet. Start communication with the Control Room Nodal Officer below.',
    replyPlaceholder: 'Type corrective actions taken, gas readings, or status update...',
    sendReply: 'Send Update',
    attachedFiles: 'Field Evidence & Inspection Photos',
    assignedLead: 'Statutory Safety Lead',
    totalIssues: 'Total Violations Logged',
    pendingReview: 'Under Inspection',
    inProgress: 'Corrective Action in Progress',
    resolvedClosed: 'Compliance Verified',
    categoryAiDistribution: 'DGMS Statutory Category Distribution',
    priorityBreakdown: 'Hazard Severity Matrix',
    sevenDayVelocity: '7-Day Violation Velocity',
    geminiWorkloadPrediction: '7-Day Predictive Hazard Surge & Compliance Risk Forecaster',
    predictiveQueueIntel: 'AI predictive intelligence identifying upcoming hazard spikes and bottleneck zones in coalfields.',
    surgeRisk: 'Surge Risk',
    primarySpike: 'Primary High-Risk Zone',
    executiveForecast: 'Operational Risk Forecast',
    staffingAction: 'Statutory Action Plan',
    searchPlaceholder: 'Search violations by title, mine pit, category or inspector...',
    categoryFilter: 'Category',
    all: 'All Categories',
    activeIssuesQueue: 'Active Compliance & Hazard Queue',
    tableIssueDetails: 'INCIDENT & MINE PIT',
    tableAiCategory: 'STATUTORY CATEGORY',
    tableAssignedLead: 'SAFETY CONTROLLER',
    tablePriority: 'SEVERITY',
    tableConfidence: 'AI CONFIDENCE',
    tableLifecycleAction: 'ACTION & STATUS',
    catSafety: 'Safety (DGMS)',
    catEnvironment: 'Environment (MoEFCC)',
    catEquipment: 'Equipment (HEMM)',
    catLabour: 'Labour & PPE Welfare',
    catProduction: 'Mining Production',
    catGeneral: 'General Operations',
    catIT: 'Safety (DGMS)',
    catHR: 'Labour & PPE Welfare',
    catFinance: 'Statutory Audit',
    catOperations: 'Mining Operations',
    prioCritical: 'CRITICAL HAZARD',
    prioHigh: 'High Severity',
    prioMedium: 'Moderate',
    prioLow: 'Low / Routine',
    statusPending: 'Under Inspection',
    statusInProgress: 'Action in Progress',
    statusResolved: 'Compliance Verified',
    statusClosed: 'Closed & Audited',
    detectLocation: 'Auto-Detect Mine Pit GPS Coordinates',
    detectingLocation: 'Acquiring satellite GPS & pit zone...',
    locationDetected: 'Pit GPS Coordinates Attached',
    removeLocation: 'Remove',
    customAddress: 'Or specify custom shaft / haul road / pit zone',
    incidentLocation: 'Geo-Tagged Pit Location',
    openInGoogleMaps: 'Open Satellite Map in Google Maps ↗',
    locationLabel: 'Location / Pit',
    backToHome: 'Back to Home'
  },
  hi: {
    appTitle: 'कोल-गार्ड (CoalGuard) OS',
    appSubtitle: 'एआई-संचालित स्मार्ट गवर्नेंस एवं डीजीएमएस अनुपालन निगरानी प्रणाली',
    adminCommandCenter: 'खदान संचालन एवं अनुपालन नियंत्रण केंद्र',
    adminSubtitle: 'AI स्वचालित विश्लेषण, डीजीएमएस ऑडिट एवं आपातकालीन संचालन हब',
    userDashboard: 'फील्ड इंस्पेक्टर / माइन वर्कर पोर्टल',
    signOut: 'लॉगआउट',
    exportCsv: 'वैधानिक ऑडिट CSV डाउनलोड करें',
    adminView: 'कमांड सेंटर',
    userView: 'इंस्पेक्टर पोर्टल',
    liveRadar: '● लाइव डीजीएमएस अनुपालन रडार — 4 खदान क्षेत्र जुड़े हैं',
    raiseIssueTitle: 'खदान सुरक्षा खतरा / उल्लंघन दर्ज करें',
    raiseIssueSubtitle: 'खदान सुरक्षा, पर्यावरण प्रदूषण या मशीनरी खराबी की रिपोर्ट जीपीएस और फोटो साक्ष्य के साथ दर्ज करें।',
    mineSiteLabel: 'कोयला खदान / साइट स्थान',
    mineSitePlaceholder: 'उदा. झरिया कोलियरी - पीट 4 (भूमिगत खदान)',
    issueTitleLabel: 'घटना / उल्लंघन का शीर्षक',
    issueTitlePlaceholder: 'उदा. शाफ्ट-बी में मीथेन गैस स्तर 1.4% या डंपर हाइड्रोलिक विफलता',
    problemDescriptionLabel: 'विस्तृत खतरा विवरण एवं फील्ड नोट्स',
    problemDescriptionPlaceholder: 'विस्तार से बताएं: सटीक पीट ज़ोन, गैस डिटेक्टर रीडिंग, प्रभावित शिफ्ट, मशीनरी नंबर...',
    attachmentsLabel: 'निरीक्षण फोटो / गैस लॉग संलग्न करें (वैकल्पिक, 5 फाइलों तक - फोटो, PDF)',
    submitButton: 'AI सुरक्षा कमांड को भेजें →',
    submittingButton: 'AI डीजीएमएस अनुपालन एवं रूटिंग विश्लेषण कर रहा है...',
    mySubmittedIssues: 'मेरे द्वारा दर्ज निरीक्षण रिपोर्ट',
    noIssuesFound: 'अभी तक कोई उल्लंघन दर्ज नहीं हुआ है। नया भू-टैग्ड निरीक्षण दर्ज करने के लिए ऊपर दिए गए फॉर्म का उपयोग करें।',
    duplicateAlertTitle: '⚠️ AI अलर्ट: इस ज़ोन में मिलता-जुलता खतरा पहले से दर्ज है!',
    duplicateAlertDesc: 'AI ने इस स्थान और खतरे से मेल खाती सक्रिय रिपोर्ट पाई है। कृपया जांचें कि क्या इस पर पहले से कार्य चल रहा है:',
    dismissContinue: 'खारिज करें और रिपोर्ट जारी रखें',
    viewMatch: 'घटना देखें →',
    problemDescription: 'खतरा एवं निरीक्षण विवरण',
    geminiExecutiveBrief: 'AI डीजीएमएस कार्यकारी सारांश',
    confidence: 'AI सटीकता',
    troubleshootingPlan: 'मानक संचालन प्रक्रिया (SOP) एवं सुरक्षा प्रोटोकॉल',
    guidance: 'कार्यवाही SOP',
    insertToReply: 'लॉग में जोड़ें',
    liveResolutionThread: 'लाइव नियंत्रण कक्ष वार्तालाप चैनल',
    noMessagesYet: 'अभी कोई संदेश नहीं है। नियंत्रण कक्ष अधिकारी के साथ बातचीत प्रारंभ करें।',
    replyPlaceholder: 'की गई सुधारात्मक कार्रवाई या गैस रीडिंग लिखें...',
    sendReply: 'अपडेट भेजें',
    attachedFiles: 'फील्ड साक्ष्य एवं निरीक्षण फोटो',
    assignedLead: 'नियुक्त सुरक्षा नियंत्रक (DGMS Lead)',
    totalIssues: 'कुल दर्ज उल्लंघन',
    pendingReview: 'निरीक्षणाधीन (Under Inspection)',
    inProgress: 'सुधार कार्य प्रगति पर (In Progress)',
    resolvedClosed: 'अनुपालन सत्यापित (Verified)',
    categoryAiDistribution: 'डीजीएमएस श्रेणी अनुसार वितरण',
    priorityBreakdown: 'खतरा गंभीरता मैट्रिक्स',
    sevenDayVelocity: '7-दिवसीय घटना गति दर',
    geminiWorkloadPrediction: '7-दिवसीय खतरा एवं अनुपालन जोखिम पूर्वानुमान',
    predictiveQueueIntel: 'खदान क्षेत्रों में आगामी खतरे और संभावित रुकावटों का पूर्वानुमान लगाने वाला AI सिस्टम।',
    surgeRisk: 'जोखिम स्तर',
    primarySpike: 'मुख्य उच्च-जोखिम क्षेत्र',
    executiveForecast: 'परिचालन जोखिम पूर्वानुमान',
    staffingAction: 'प्रबंधन कार्ययोजना',
    searchPlaceholder: 'शीर्षक, खदान पीट, श्रेणी या इंस्पेक्टर से खोजें...',
    categoryFilter: 'श्रेणी',
    all: 'सभी श्रेणियां',
    activeIssuesQueue: 'सक्रिय अनुपालन एवं खतरा सूची',
    tableIssueDetails: 'घटना एवं खदान पीट',
    tableAiCategory: 'वैधानिक श्रेणी',
    tableAssignedLead: 'सुरक्षा नियंत्रक',
    tablePriority: 'गंभीरता',
    tableConfidence: 'AI सटीकता',
    tableLifecycleAction: 'कार्रवाई व स्थिति',
    catSafety: 'सुरक्षा (DGMS Safety)',
    catEnvironment: 'पर्यावरण (MoEFCC)',
    catEquipment: 'मशीनरी (HEMM Equipment)',
    catLabour: 'श्रमिक कल्याण एवं पीपीई',
    catProduction: 'कोयला उत्पादन (Production)',
    catGeneral: 'सामान्य परिचालन',
    catIT: 'सुरक्षा (DGMS Safety)',
    catHR: 'श्रमिक कल्याण एवं पीपीई',
    catFinance: 'वैधानिक ऑडिट',
    catOperations: 'कोयला उत्पादन',
    prioCritical: 'अत्यंत गंभीर खतरा (CRITICAL)',
    prioHigh: 'उच्च गंभीरता (High)',
    prioMedium: 'मध्यम (Moderate)',
    prioLow: 'सामान्य / नियमित',
    statusPending: 'निरीक्षणाधीन (Pending)',
    statusInProgress: 'सुधार प्रगति पर',
    statusResolved: 'अनुपालन सत्यापित (Resolved)',
    statusClosed: 'बंद एवं ऑडिट पूर्ण',
    detectLocation: 'खदान पीट जीपीएस (GPS) स्थान पता करें',
    detectingLocation: 'सैटेलाइट जीपीएस व पीट क्षेत्र प्राप्त किया जा रहा है...',
    locationDetected: 'पीट जीपीएस निर्देशांक संलग्न',
    removeLocation: 'हटाएं',
    customAddress: 'या विशिष्ट शाफ्ट / हॉल रोड / पीट ज़ोन लिखें',
    incidentLocation: 'भू-टैग्ड खदान स्थान',
    openInGoogleMaps: 'गूगल सैटेलाइट मैप पर देखें ↗',
    locationLabel: 'स्थान / पीट',
    backToHome: 'होम पेज पर जाएं'
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('smart_issue_lang') || 'en';
  });

  const toggleLang = (selectedLang) => {
    const newLang = selectedLang || (lang === 'en' ? 'hi' : 'en');
    setLang(newLang);
    localStorage.setItem('smart_issue_lang', newLang);
  };

  const t = (key) => {
    return translations[lang]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
